### PR TITLE
Errored oembed bugfix

### LINKED ISSUE #195: Manage oEmbeds Dashboard link fails when 0 works have oEmbed
### Descriptive summary

If no works have been created yet that have an oEmbed URL, clicking Manage oEmbeds in the Dashboard throws an error: 

```
Blacklight::Exceptions::InvalidRequest in OregonDigital::Oembeds#index
Showing /data/app/views/oregon_digital/oembeds/_list_errored_oembeds.html.erb where line #1 raised:

RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"zkConnected":true,"status":400,"QTime":2,"params":{"fq":"id:()","sort":"system_create_dtsi desc","rows":"1000","wt":"json"}},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.parser.ParseException"],"msg":"org.apache.solr.search.SyntaxError: Cannot parse 'id:()': Encountered \" \")\" \") \"\" at line 1, column 4.\nWas expecting one of:\n    <NOT> ...\n    \"+\" ...\n    \"-\" ...\n    <BAREOPER> ...\n    \"(\" ...\n    \"*\" ...\n    <QUOTED> ...\n    <TERM> ...\n    <PREFIXTERM> ...\n    <WILDTERM> ...\n    <REGEXPTERM> ...\n    \"[\" ...\n    \"{\" ...\n    <LPARAMS> ...\n    \"filter(\" ...\n    <NUMBER> ...\n    <TERM> ...\n    ","code":400}}

URI: http://solr-dev:8983/solr/development/select?wt=json&&&&fq=id%3A%28%29&&rows=1000&sort=system_create_dtsi+desc
```

### Expected behavior

Manage oEmbeds should display empty but correct Dashboard page.

### PR DESCRIPTION
**Pull request by revgum**
fixes #195

### CODE REVIEW

File: app/search_builders/oregon_digital/errored_oembed_search_builder.rb [hunk 1]
```diff
@@ -6,9 +6,11 @@ class ErroredOembedSearchBuilder < OembedSearchBuilder
     self.default_processor_chain += [:with_errored_oembed]
 
     def with_errored_oembed(solr_params)
-      error_ids = OembedError.all.map(&:document_id).join(' OR ')
+      ids = OembedError.all.map(&:document_id).join(' OR ')
       solr_params[:fq] ||= []
-      solr_params[:fq] = "id:(#{error_ids})"
+      query = solr_params[:fq].length.zero? ? '' : ' AND '
+      filter = ids.blank? ? '-id:*' : "id:(#{ids})"
+      solr_params[:fq] << "#{query}#{filter}"
```
Comment (CGillen) [inline app/search_builders/oregon_digital/errored_oembed_search_builder.rb]: `solr_params[:fq]` is supposed to be an array, but comes back as a string from OembedSearchBuilder, similar to Hyrax code: https://github.com/samvera/hyrax/blob/master/app/search_builders/hyrax/embargo_search_builder.rb#L17
This is causing inconsistent behavior between actually running (string) and testing (array)
changing L18 of OembedSearchBuilder to `solr_params[:fq] << 'oembed_url_tesim:*'`, removing `query` here, and updating tests should fix the issue
